return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    spec = {
      { "<leader>D",  group = "Diff" },
      { "<leader>o",  group = "Octo" },
      { "<leader>op", group = "PR" },
      { "<leader>or", group = "Review" },
      { "<leader>a",  group = "Avante" },
      { "<leader>A",  group = "Copilot" },
      { "<leader>b",  group = "Buffer" },
      { "<leader>f",  group = "Find" },
      { "<leader>g",  group = "Git" },
      { "<leader>gl", group = "Linker" },
      { "<leader>h",  group = "GitSigns" },
      { "<leader>i",  group = "DAP" },
      { "<leader>k",  group = "Docs" },
      { "<leader>l",  group = "LSP" },
      { "<leader>L",  group = "Chainsaw" },
      { "<leader>n",  group = "Notes" },
      { "<leader>r",  group = "Repl" },
      { "<leader>q",  group = "Snippets" },
      { "<leader>t",  group = "Test" },
      { "<leader>u",  group = "UI" },
      { "<leader>w",  group = "Window" },
      { "<leader>x",  group = "Trouble" },
      { "<C-'>",      "<C-w>v",                                   desc = "Split Vertical" },
      { "<C-;>",      "<C-w>s",                                   desc = "Split Horizontal" },
      { "<C-n>",      "<cmd>BufferNext<cr>",                      desc = "Next Buffer" },
      { "<C-p>",      "<cmd>BufferPrevious<cr>",                  desc = "Previous Buffer" },
      { "<Esc>",      "<C-\\><C-n>",                              desc = "Escape Terminal Mode", mode = "t" },
      { "<Left>",     "<cmd>5winc <<cr>",                         desc = "Shift Pane Left" },
      { "<Right>",    "<cmd>5winc ><cr>",                         desc = "Shift Pane Right" },
      { "<leader>p",  '"+p',                                      desc = "Paste" },
      { "<leader>P",  '"+P',                                      desc = "Paste" },
      { "<leader>e",  function() vim.diagnostic.open_float() end, desc = "Open Float" },
      { "<leader>wo", "<C-w>o",                                   desc = "Close Other Windows" },
      { "<leader>wp", "<cmd>pclose<cr>",                          desc = "ClosePreview" },
      { "<leader>wz", "<C-w>|<C-w>_",                             desc = "Maximize" },
      { "<leader>y",  '"+y',                                      desc = "Yank",                 mode = { "n", "v" } },
      { "<leader>z",  "<cmd>Lazy update<cr>",                     desc = "Lazy Update" },
      { "ZZ",         "<cmd>wqa!<cr>",                            desc = "Save and Quit" },
      { "[l",         "<cmd>lprevious<CR>",                       desc = "Previous Location" },
      { "[q",         "<cmd>cprevious<CR>",                       desc = "Previous Quickfix" },
      { "]l",         "<cmd>lnext<CR>",                           desc = "Next Location" },
      { "]q",         "<cmd>cnext<CR>",                           desc = "Next Quickfix" },
    }
  },
}
